CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE login_session (
  ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  uid BIGINT NOT NULL REFERENCES user_(uid),
  expires_at TIMESTAMPTZ DEFAULT (CURRENT_TIMESTAMP + INTERVAL '12 hour')
);
